### ISSUE TITLE
Strange issue...

### ISSUE THREAD

**Issue by MatthewStevenGo** [llbit/chunky#380] opened 2016-09-11 04:38 UTC
![strange issue](https://cloud.githubusercontent.com/assets/12709542/18415210/c027f80c-781c-11e6-9401-31ce859d1f06.png)
I tried to render the buildings but it does not show up.

**Comment by empirebuilder1** [comment] 2016-09-11 16:39
Click "Load Selected Chunks" in the render controls window. Also make sure the loaded scenery isn't actually behind the camera.  

Please use the subreddit for general help items. www.reddit.com/r/chunky

**Comment by llbit** [comment] 2016-09-11 18:23
It looks like the Y cutoff setting may be above all of the blocks in your Minecraft world, thus excluding all of them when loading chunks.

It is strange that the Y cutoff value is not displayed in the text field next to the slider. Please try moving the slider to the far left and reloading the chunks or create a new scene.

Minecraft creates flat worlds near the bottom of the Y axis.

**Comment by MatthewStevenGo** [comment] 2016-09-12 03:41
Oh. Thanks. :)

**Comment by MatthewStevenGo** [comment] 2016-09-12 03:41
I just did not know the Y cutoff thing. :)

**Comment by llbit** [comment] 2016-09-14 11:33
I'm closing this because it seems like the issue is fixed now.

**Closed by llbit** 2016-09-14 11:33 UTC
Labels: need more info

**Comment by paddotk** [comment] 2020-09-26 16:20
Could someone tell me where the Y cutoff option is exactly? I checked every tab in the render controls window, but don't see it. Wherever I move the camera to, the render is always just a gray square.
