### ISSUE TITLE
World not loading properly

### ISSUE THREAD

**Issue by PolZol** [llbit/chunky#516] opened 2019-02-26 19:42 UTC
In version 1.4.5, I can not make any renders of Minecraft 1.13 worlds because the preview just shows empty or blue chunks (ocean). It happens in every world, and there is not any ocean where the program displays it.

**Comment by llbit** [comment] 2019-02-26 19:43
This is a known issue/duplicate of #463

**Closed by llbit** 2019-02-26 19:43 UTC
Labels: duplicate
