### ISSUE TITLE
Texture pack error in Chunky

### ISSUE THREAD

**Issue by Flash12** [llbit/chunky#413] opened 2017-01-27 19:09 UTC
Every time I try to open a 1.8 or newer texture pack, it gives this error and I can't figure out why it's doing that. The pack opens up fine in Minecraft but not in Chunky. I even downgraded Chunky to 1.3.8 to see if it still did it and it does. 

![capture2](https://cloud.githubusercontent.com/assets/11202830/22384038/8d2e6bd0-e49a-11e6-95d0-09b4f40e1ce0.JPG)

**Comment by llbit** [comment] 2017-02-02 13:59
Which texture pack are you using?

This error message happens because the resource pack is expected to have a top-level directory called "assets". If the resource pack works with Minecraft then maybe Chunky should allow the asset directory to be optional. I haven't seen any texture packs that don't have the asset directory.

**Comment by SpartanOverdrive** [comment] 2017-06-23 13:32
I'm having the same error with every resource pack I try. My top level directory
 is assets, so I'm really not sure what the issue is. I've even uninstalled and reinstalled Chunky. Any help would be greatly appreciated!
![asset folder](https://user-images.githubusercontent.com/29659209/27484347-7e49798a-57ee-11e7-835f-52203fe98f2d.JPG)

**Comment by llbit** [comment] 2017-06-25 20:15
I looked at the "Faithful + Overdrive" resource pack from @SpartanOverdrive and the top-level directory was actually named the same as the Zip file, with the assets directory inside that.

I have added an extra check for this in Chunky so that it can work with Zip files that have a top-level directory with the same name as the Zip file.

**Comment by llbit** [comment] 2017-08-02 09:16
This should be fixed in Chunky version 1.4.3+.

**Closed by llbit** 2017-08-02 09:16 UTC
