### ISSUE TITLE
[Feature Request][Maybe impossible] Custom ID map, modded block support?

### ISSUE THREAD

**Issue by ReikaKalseki** [llbit/chunky#354] opened 2016-01-31 21:31 UTC
Is it at all possible (and reasonable) to implement the ability to use custom ID maps (such as for older MC versions or modded instances)?

Also, depending on how Chunky does its rendering, is support for modded blocks at all implementable?

**Comment by llbit** [comment] 2016-09-20 07:01
This is a duplicate of issue #88

**Closed by llbit** 2016-09-20 07:01 UTC
Labels: duplicate
