### ISSUE TITLE
Can't add player at target (Exception)

### ISSUE THREAD

**Issue by fusionlightcat** [llbit/chunky#363] opened 2016-05-11 18:54 UTC
Hello!

Everytime I try to use the "+"-Button to add a new player entity at the target position I get the following exception in the debug console (verbose logging enabled):

```
Settings loaded from /home/arthur/bin/chunky/chunky.json
Loading textures from /home/arthur/.minecraft/versions/1.8.8-OptiFine_HD_U_G7/1.8.8-OptiFine_HD_U_G7.jar
Found Minecraft directory /home/arthur/.minecraft
Found latest Minecraft version: /home/arthur/.minecraft/versions/1.9.2/1.9.2.jar
Failed to load textures from texture pack (/home/arthur/.minecraft/versions/1.8.8-OptiFine_HD_U_G7/1.8.8-OptiFine_HD_U_G7.jar):
	grass_path_side
	chorus_plant
	end_rod
	chorus_flower
	purpur_pillar
	grass_path_top
	end_bricks
	purpur_block
	chorus_flower_dead
	purpur_pillar_top

Could not read player data file '/home/arthur/storage/w2cmap/main/playerdata/bkup'
Saved settings to /home/arthur/bin/chunky/chunky.json
Settings loaded from /home/arthur/bin/chunky/chunky-launcher.json
Loading sky map: /home/arthur/skybox/sky_day03_05up.png
Preprocessing skymap texture
Skymap preprocessing took 95ms
Loading sky map: /home/arthur/skybox/sky_day03_05dn.png
Preprocessing skymap texture
Skymap preprocessing took 42ms
Loading sky map: /home/arthur/skybox/sky_day03_05rt.png
Preprocessing skymap texture
Skymap preprocessing took 40ms
Loading sky map: /home/arthur/skybox/sky_day03_05lf.png
Preprocessing skymap texture
Skymap preprocessing took 38ms
Loading sky map: /home/arthur/skybox/sky_day03_05ft.png
Preprocessing skymap texture
Skymap preprocessing took 39ms
Loading sky map: /home/arthur/skybox/sky_day03_05bk.png
Preprocessing skymap texture
Skymap preprocessing took 48ms
Could not read player data file '/home/arthur/storage/w2cmap/main/playerdata/bkup'
Loading render dump server_soehavn_westhafen_5.dump
Render dump loaded
Loading octree server_soehavn_westhafen_5.octree
Octree loaded
Loading grass texture server_soehavn_westhafen_5.grass
Grass texture loaded
Loading foliage texture server_soehavn_westhafen_5.foliage
Foliage texture loaded
buffer finalization enabled
Exception in thread "AWT-EventQueue-0" java.lang.UnsupportedOperationException
	at java.util.AbstractMap.put(AbstractMap.java:209)
	at se.llbit.chunky.renderer.scene.Scene.addPlayer(Scene.java:2335)
	at se.llbit.chunky.renderer.ui.tabs.EntitiesTab$12.actionPerformed(EntitiesTab.java:406)
	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
	at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2348)
	at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
	at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)
	at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:252)
	at java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:289)
	at java.awt.Component.processMouseEvent(Component.java:6533)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
	at java.awt.Component.processEvent(Component.java:6298)
	at java.awt.Container.processEvent(Container.java:2236)
	at java.awt.Component.dispatchEventImpl(Component.java:4889)
	at java.awt.Container.dispatchEventImpl(Container.java:2294)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4888)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4525)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4466)
	at java.awt.Container.dispatchEventImpl(Container.java:2280)
	at java.awt.Window.dispatchEventImpl(Window.java:2746)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.awt.EventQueue$4.run(EventQueue.java:731)
	at java.awt.EventQueue$4.run(EventQueue.java:729)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

I am using Chunky release 1.3.8 with Java 1.8.0_92 on Linux Mint 17.1 64bit (Ubuntu based) with kernel version 3.13.0-53.

Thanks in advance! :)

**Comment by llbit** [comment] 2016-08-22 10:23
When the player list is empty it is not possible to add new player entities. If there is at least one player loaded in the scene (enable "load players"), then it should work.

This has been fixed in the snapshot 1.4.0-alpha2. The bug was caused by the profile map being initialized to an unmodifiable empty map.

**Closed** 2016-09-11 16:37 UTC
Labels: bug
