### ISSUE TITLE
ArrayIndexOutOfBoundsException: -3 when rendering a large scene (around 600k chunks)

### ISSUE THREAD

**Issue by stormboomer** [llbit/chunky#624] opened 2020-07-06 19:16 UTC
When trying to render a large scene (around 600k Chunks) from a scene file only (no pregenerated octree) I am getting an ArrayIndexOutOfBoundsException.

This seems to have to do with the new PackedOctree generation. When using NodeBasedOctree the issue does not seem to occur.

I think that this might have to do with the switch between implementation of NodeBasedOctree and PackedOctree, the switch happens around 400k Chunks

```
Loading chunks: 76.4% (460,741 of 602,866)
Octree is too big, falling back to old (slower and bigger) implementation.
Loading chunks: 100.0% (602,866 of 602,866)
Loading chunks took 53m 9s1)
Finalizing octree took 0m 0s          
Loading scene took 53m 26s

Unchecked exception caused Chunky to close.
java.lang.NullPointerException
	at se.llbit.math.NodeBasedOctree.get(NodeBasedOctree.java:133)
	at se.llbit.math.NodeBasedOctree.getMaterial(NodeBasedOctree.java:141)
	at se.llbit.math.Octree.getMaterial(Octree.java:292)
	at se.llbit.chunky.renderer.scene.OctreeFinalizer.processBlock(OctreeFinalizer.java:58)
	at se.llbit.chunky.renderer.scene.OctreeFinalizer.finalizeChunk(OctreeFinalizer.java:50)
	at se.llbit.chunky.renderer.scene.Scene.loadChunks(Scene.java:969)
	at se.llbit.chunky.renderer.scene.Scene.loadScene(Scene.java:508)
	at se.llbit.chunky.renderer.scene.SynchronousSceneManager.loadScene(SynchronousSceneManager.java:146)
	at se.llbit.chunky.main.Chunky.doHeadlessRender(Chunky.java:164)
	at se.llbit.chunky.main.Chunky.main(Chunky.java:213)

```

**Comment by leMaik** [comment] 2020-07-24 22:27
This issue was probably caused by a bug when converting the octree from packed to node-based. Since the conversion now uses the store and load methods, this should be fixed.

**Closed by leMaik** 2020-07-24 22:27 UTC
Labels: bug, chunky 2.x
