### ISSUE TITLE
NullPointerException when starting without Minecraft installed

### ISSUE THREAD

**Issue by leMaik** [llbit/chunky#308] opened 2015-02-23 11:30 UTC
I tried to start Chunky in headless mode without having Minecraft installed. If I don't specify a texturepack, everything works as expected (black boxes with crosses whenever a texture is missing). If I use a texturepack with the `-texture` option, Chunky crashes with an NPE.
I'm using the latest chunky version.

Expected behaviour: Use the specified texture pack and fall back to *black boxes with red crosses* if a texture is missing, but don't crash.

**Comment by llbit** [comment] 2015-03-21 14:25
Can you post the stack trace please?

**Comment by leMaik** [comment] 2015-03-26 00:03
I'm afraid I can't reproduce the problem. When I opened this issue, I couldn't get it to work, now I can't get it not to work.
Sorry! :-(

**Comment by llbit** [comment] 2015-03-26 16:17
I tried to reproduce the problem myself but could not. If I can't reproduce it I'm afraid there is nothing I can do to fix it, except looking hard at the code to find bugs but that is usually a waste of time.

I'll close this issue now, but please reopen it if you find a way to reproduce the error!

**Closed by llbit** 2015-03-26 16:17 UTC
Labels: need more info
